name             'masala_spark'
maintainer       'Joe Hohertz'
maintainer_email 'jhohertz@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures masala_spark'
long_description 'Installs/Configures masala_spark'
version          '0.1.0'

depends          'masala_base', '~> 0.1.0'
depends          'masala_ldap', '~> 0.1.0'
depends          'apache_spark', '~> 1.2.12'
depends          'ulimit',  '~> 0.3.3'
